"""
Django settings for {{ cookiecutter.project_name_lat }} project.

Generated by Cookiecutter using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy  # PREP

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wq_x*w%6zxwi@ux#(gmfq*ije&jy-g*p7(0z@)fy2yef9@b1c%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # PREP {
    "jquery",
    "django_bootstrap_icons",
    # } PREP
    "home",  # PREP
    "general",  # PREP
    # PREP {
    # Должно быть крайним в списке. См. https://pypi.org/project/django-cleanup/
    "django_cleanup.apps.CleanupConfig",
    # } PREP
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # PREP {
    # Для упрощения.
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # } PREP
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "{{ cookiecutter.project_slug }}.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "general.context_processors.app_name",  # PREP
            ],
        },
    },
]

WSGI_APPLICATION = "{{ cookiecutter.project_slug }}.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PREP {

{% if cookiecutter.db_username and cookiecutter.db_password -%}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "{{ cookiecutter.student_slug }}_{{ cookiecutter.project_slug }}",
        "USER": "{{ cookiecutter.db_username }}",
        "PASSWORD": "{{ cookiecutter.db_password }}",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}
{% else -%}
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
{% endif %}

# } PREP

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru"  # PREP

TIME_ZONE = (
    "Europe/Moscow"  # PREP https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
)

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# PREP {

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

PASSWORD_HASHERS = [
    "plaintext_password.PlaintextPasswordHasher",
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = reverse_lazy("login")

APP_NAME = "{{ cookiecutter.project_name_rus }}"  # PREP Наименование приложения. Используется по необходимости.

# } PREP
